act0: false
act1: true
act2: false
act3: false
act4: true
dp0_0: 0.8
dp0_1: 0.5
dp1: 0.1
dp2: 0.0
dp3: 0.0
epoch: 2000
hidden_dim_1: 48
hidden_dim_2: 18
layer1: 2
layer2: 1
layer3: 2
ln0: true
ln1: false
ln2: false
ln3: true
ln4: true
lr: 0.01
